version: "3.8"

services:
  trading-card-service:
    build:
      context: .
    image: trading-card-service
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - 3000:3000
